// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOrlNPElHRdrLYlgPy0N9qaHyn0SrSxo',
    appId: '1:49538736864:web:af20bd188adec3b6562685',
    messagingSenderId: '49538736864',
    projectId: 'furever-home-19609',
    authDomain: 'furever-home-19609.firebaseapp.com',
    storageBucket: 'furever-home-19609.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsMczq52KW6sd8y0ffSuIOjobbjHZ3mUA',
    appId: '1:49538736864:android:4929d92c4264af5d562685',
    messagingSenderId: '49538736864',
    projectId: 'furever-home-19609',
    storageBucket: 'furever-home-19609.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQOrlNPElHRdrLYlgPy0N9qaHyn0SrSxo',
    appId: '1:49538736864:web:af20bd188adec3b6562685',
    messagingSenderId: '49538736864',
    projectId: 'furever-home-19609',
    authDomain: 'furever-home-19609.firebaseapp.com',
    storageBucket: 'furever-home-19609.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDozzmKyhTTi-FXLEtHsws50ZLGbl3-sks',
    appId: '1:49538736864:ios:4a76583939e74cb8562685',
    messagingSenderId: '49538736864',
    projectId: 'furever-home-19609',
    storageBucket: 'furever-home-19609.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterProjects',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDozzmKyhTTi-FXLEtHsws50ZLGbl3-sks',
    appId: '1:49538736864:ios:4a76583939e74cb8562685',
    messagingSenderId: '49538736864',
    projectId: 'furever-home-19609',
    storageBucket: 'furever-home-19609.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterProjects',
  );

}